---
version: '2.3'
services:
  kubeadm-terraform:
    build:
      context: .
      dockerfile: terraform-Dockerfile
    privileged: true
    userns_mode: "host"
    volumes:
      - "$HOME/.aws:/root/.aws"
      - "./aws-kubeadm-terraform:/aws-kubeadm-terraform"
      - "/dev:/dev"
    #working_dir: /aws-kubeadm-terraform
    environment:
      - AWS_DEFAULT_REGION
      - AWS_PROFILE
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN

  awscli:
    image: xueshanf/awscli:latest
    volumes:
      - ".:/build"
      - "$HOME/.aws:/root/.aws"
    working_dir: /build
    environment:
      - AWS_DEFAULT_REGION
      - AWS_PROFILE
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN

