name: CI to Docker hub 

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: node-web
  DOCKER_REGISTRY: docker.io

jobs:
  build_push_docker:
    runs-on: ubuntu-latest
    name: Build and push docker image to docker.io

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set version from package.json
        run: |
          version=$(grep version package.json | awk -F':' '{ print $2 }' | sed 's/[", ]//g')
          echo '::set-output name=VERSION::$version'
        id: package-json-version

      - name: Docker build image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE_NAME:${{ steps.package-json-version.outputs.VERSION }}

      - name: Push image to docker.io
        run: docker push $DOCKER_REGISTRY/${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE_NAME:${{ steps.package-json-version.outputs.VERSION }}

