name: CI to Docker hub 

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: node-web

jobs:
  build_push_docker:
    runs-on: ubuntu-latest
    name: Build and push docker image to docker.io

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Docker build image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE_NAME:latest

      - name: Push image to docker.io
        run: docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE_NAME:latest


